In [1]:
seq= ['soup','dog','salad','cat','great']

In [2]:
list(filter(lambda word: word[0]=='s',seq))

['soup', 'salad']

In [3]:
def caught_speeding(speed,is_birthday):
    if is_birthday:
        speeding=speed-5
    else:
        speeding=speed
    if speeding>80:
        return 'big ticket'
    elif speeding>60:
        return 'small ticket'
    else:
        return 'no ticket'
        

In [4]:
caught_speeding(81,True)

'small ticket'

In [5]:
caught_speeding(81,False)

'big ticket'

In [6]:
'hello'

'hello'

In [7]:
print('hello')

hello


In [8]:
v=10

In [9]:
v

10

In [10]:
lst=[1,2,3]

In [11]:
lst

[1, 2, 3]

In [12]:
import numpy as np

In [13]:
arr=np.array(lst)

In [14]:
arr

array([1, 2, 3])

In [15]:
my_mat=[[1,2,3],[4,5,6],[6,7,8]]

In [16]:
my_mat

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]

In [17]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [23]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.82184177, 0.99627344, 0.86024689, 0.58153664, 0.16977431])

In [26]:
np.random.rand(5,5)

array([[0.62644761, 0.12513181, 0.17997135, 0.74990515, 0.44671024],
       [0.87046854, 0.86243771, 0.73036246, 0.15130358, 0.90439763],
       [0.4611802 , 0.90446954, 0.5898153 , 0.54695764, 0.07169708],
       [0.24048828, 0.28446568, 0.06081164, 0.06840896, 0.62607634],
       [0.90983665, 0.64524027, 0.45732015, 0.6745986 , 0.1662464 ]])

In [27]:
np.random.randn(2)

array([0.62253719, 0.02353857])

In [28]:
np.random.randn(2,2)

array([[ 0.09645813, -1.03163344],
       [-1.50677544,  0.57180289]])

In [29]:
np.random.randint(1,100,5)

array([69, 72, 14, 24, 19])

In [30]:
arr=np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr=np.random.randint(0,50,10)

In [33]:
ranarr

array([38, 24, 34,  3, 39, 24,  1, 37,  2, 28])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr

array([38, 24, 34,  3, 39, 24,  1, 37,  2, 28])

In [36]:
ranarr.max()

39

In [37]:
ranarr.min()

1

In [38]:
ranarr.argmax()

4

In [39]:
ranarr.argmin()

6

In [40]:
arr.shape

(25,)

In [41]:
arr=arr.reshape(5,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.dtype

dtype('int32')

In [44]:
from numpy.random import randint

In [45]:
randint(2,10)

6