In [1]:
import numpy as np

In [2]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((4,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.linspace(0,4,4)

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [15]:
np.random.rand(5)

array([0.69544419, 0.87356006, 0.6228847 , 0.77451072, 0.85828958])

In [16]:
np.random.rand(4,4)

array([[0.34519792, 0.38037925, 0.79473948, 0.12713983],
       [0.58631406, 0.71741752, 0.73982582, 0.9860161 ],
       [0.07113812, 0.43856935, 0.57561267, 0.75768509],
       [0.92088536, 0.4327139 , 0.12015681, 0.88990266]])

In [17]:
np.random.randint(1,100)

13

In [18]:
np.random.rand(1,100)

array([[0.65330294, 0.04582118, 0.87776281, 0.45112749, 0.94594236,
        0.66475201, 0.67738232, 0.58987086, 0.01578538, 0.29738207,
        0.82203075, 0.92659431, 0.60255138, 0.51503123, 0.35112342,
        0.89374188, 0.05714197, 0.70954351, 0.02000638, 0.09110982,
        0.53661001, 0.46885512, 0.45179161, 0.23795336, 0.57980991,
        0.60127912, 0.98748837, 0.42468762, 0.79506637, 0.42799871,
        0.75287539, 0.95773281, 0.68577363, 0.71353264, 0.95911034,
        0.18071121, 0.28315258, 0.08366011, 0.73882229, 0.46577534,
        0.13627743, 0.41867829, 0.41688344, 0.35450059, 0.12919607,
        0.19120115, 0.49292227, 0.26125555, 0.60447623, 0.85568283,
        0.13361495, 0.07233756, 0.30105131, 0.38412254, 0.72277235,
        0.40540786, 0.36572665, 0.1182301 , 0.12084234, 0.15483425,
        0.85063746, 0.70670627, 0.61285368, 0.91788549, 0.79562502,
        0.85124466, 0.00759676, 0.00425247, 0.61255115, 0.49730781,
        0.71152721, 0.35355746, 0.2456333 , 0.01

In [19]:
np.random.randint(1,100,10)

array([24, 90, 23, 17, 42, 96, 74, 16, 20, 89])

In [20]:
ranarr=np.random.randint(0,50,10)

In [21]:
ranarr.reshape(10,1)

array([[ 7],
       [ 4],
       [27],
       [44],
       [14],
       [18],
       [ 7],
       [38],
       [27],
       [36]])

In [34]:
arr=[1,2,3,4,5,6,7]

In [35]:
ranarr.argmax()

3

In [36]:
ranarr.argmin()

1

In [37]:
ranarr

array([ 7,  4, 27, 44, 14, 18,  7, 38, 27, 36])